name: call_of_duty_mobile_guide
description: Call of Duty Mobile Ultimate Guide

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/about.jpg
    - assets/images/attachments.jpg
    - assets/images/guns.jpg
    - assets/images/throwables.png
    - assets/images/tips.png
    - assets/images/weapons/
    - assets/images/throwables/
